"""empty message

Revision ID: 031e4e0057e0
Revises: fdb1d94cf23e
Create Date: 2021-02-22 16:53:33.049146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e4e0057e0'
down_revision = 'fdb1d94cf23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_talent', sa.Column('img_url', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'mood', ['date_published'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mood', type_='unique')
    op.drop_column('human_talent', 'img_url')
    # ### end Alembic commands ###
