"""empty message

<<<<<<< HEAD:migrations/versions/03944245c0e7_.py
Revision ID: 03944245c0e7
Revises: 
Create Date: 2021-02-17 18:47:50.995560
=======
Revision ID: 3bdc42f7efa4
Revises: 
Create Date: 2021-02-24 23:20:59.526585
>>>>>>> 5294cf5fd87c25155b0776def66374716241fe57:migrations/versions/3bdc42f7efa4_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/03944245c0e7_.py
revision = '03944245c0e7'
=======
revision = '3bdc42f7efa4'
>>>>>>> 5294cf5fd87c25155b0776def66374716241fe57:migrations/versions/3bdc42f7efa4_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('hr_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashed_password'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('human_talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
<<<<<<< HEAD:migrations/versions/03944245c0e7_.py
=======
    sa.Column('img_url', sa.String(length=120), nullable=True),
>>>>>>> 5294cf5fd87c25155b0776def66374716241fe57:migrations/versions/3bdc42f7efa4_.py
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_published', sa.DateTime(timezone=True), nullable=False),
    sa.Column('face_value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('human_talent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['human_talent_id'], ['human_talent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood')
    op.drop_table('human_talent')
    op.drop_table('team')
    op.drop_table('hr_manager')
    op.drop_table('company')
    # ### end Alembic commands ###
