"""empty message

Revision ID: c3137fca47fb
Revises: 19a7cf96874b
Create Date: 2021-02-23 10:55:27.409335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3137fca47fb'
down_revision = '19a7cf96874b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood', 'date_published',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood', 'date_published',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
