"""empty message

Revision ID: e465a1549511
Revises: c3137fca47fb
Create Date: 2021-02-23 21:37:59.239624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e465a1549511'
down_revision = 'c3137fca47fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood', 'date_published',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mood', 'date_published',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
