"""empty message

Revision ID: fdb1d94cf23e
Revises: 87f5497b3f71
Create Date: 2021-02-18 21:03:28.970936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb1d94cf23e'
down_revision = '87f5497b3f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
